# Generated by Django 5.1.1 on 2024-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
